print("hello my name is khizar hayat")
print("hello my name is khizar hayat")
print("khizar hayat")
print("sdjfjdfjsdj")
print("sdjfjdfjsdj")
print("sdjfjdfjsdj")
print("sdjfjdfjsdj")
print("sdjfjdfjsdj")
print("sdjfjdfjsdj")
print("sdjfjdfjsdj")
print("sdjfjdfjsdj")
print("sdjfjdfjsdj")
print("sdjfjdfjsdj")
print("sdjfjdfjsdj")
print("sdjfjdfjsdj")
print("sdjfjdfjsdj")
print("sdjfjdfjsdj")
print("sdjfjdfjsdj")
print("sdjfjdfjsdj")
print("sdjfjdfjsdj")
print("sdjfjdfjsdj")
print("sdjfjdfjsdj")